### ISSUE TITLE
"Elaborated Expression" and "Type of Expression" doesn't work correctly in \class and \record

### ISSUE THREAD

**Issue by tonyxty** [JetBrains/intellij-arend#231]
Consider the following code:
````arend
\record Foo
  | bar (A : \Set) (B : \Type1) (a : A) (b : B) : B
--           ^1         ^2           ^3      ^4
````
If I move the cursor to positions marked as ^1, ^2, ^3, and ^4 and execute "Elaborated Expression" and "Type of Expression" respectively,
Expected results: `\Set`, `\1-Type`, `\Type1`, `\Type2`, `A`, `\Set`, `B`, `\Type1`
Actual results: (error), (error), `\Set`, `\1-Type`, `\Type1`, `\Type2`, `A`, `\Set`

This also happens if I replace `\record` with `\class`.  Apparently the actual results is one place off from the expected results.

**Comment by ice1000** [comment]
Explanation:

This issue occurs because in the compiler, I remove one of the parameters from the concrete definition:
https://github.com/JetBrains/Arend/blob/1643c254fad44f11b0e063400e6005497e98830f/base/src/main/java/org/arend/typechecking/subexpr/CorrespondedSubDefVisitor.java#L116-L118

This assumes the definition is desugared, so an `\this` parameter is inserted. To compare it with the concrete definition, we need to make the parameters isomorphic, so we remove the first `\this` parameter.

However, in the IDE, the concrete definitions are **not** desugared. Thus, a parameter is removed for nothing. I have fixed it in the compiler, and I'll add a test soon.

**Comment by ice1000** [comment]
Oh well, I didn't expect a commit in Arend will close this...
