### ISSUE TITLE
Bug: "Replace with constructor" removes code after hole

### ISSUE THREAD

**Issue by marat-rkh** [JetBrains/intellij-arend#299]
```tex
\open Nat (+)

\func example : Nat => {?} + {?}
```
Call "Replace with constructor" on the first hole, select "zero", press Enter.

Expected: 
```tex
\func example : Nat => zero + {?}
```
Actual: 
```tex
\func example : Nat => zero
```
As you can see, `+ {?}` was removed, which is incorrect.

**Comment by valis** [comment]
It's a bug in BasePass. At line 195 we pass `expr.textRange` to `replaceExprSmart`, but that's incorrect since we need to compute the actual deleted range. I think this functionality was already implemented in https://github.com/JetBrains/intellij-arend/pull/281. So, we need to wait until it's merged.

**Comment by marat-rkh** [comment]
`org.arend.util.ArendBinOpUtilsKt#getBounds` might help with this issue.
