### ISSUE TITLE
Wrong syntax but successful typechecks

### ISSUE THREAD

**Issue by xamgore** [JetBrains/intellij-arend#36]
Plugin doesn't show any warnings, is it an expected behaviour? I have the latest plugin & compiler version. `2/2` tests are the first two functions in [this file](https://github.com/valis/DT2018/blob/master/proj03/src/hw03.vc). The following functions are not typechecked :disappointed: 

![image](https://user-images.githubusercontent.com/4586392/45849052-4dbfc880-bd39-11e8-89dc-eb26b6e66d84.png)

```
\data T (b : Bool)
  | false => Empty
  | true  => Unit
```

**Comment by valis** [comment]
This is indeed an expected behaviour. This is an incorrect syntax, so the part after `| false` is simply ignored. Thus, the typechecker sees this definition as `\data T (b : Bool) | false` and typechecks it without problems. The typechecker does not always report parser errors, so you need to fix them before the typechecking.

**Comment by xamgore** [comment]
thanks :+1:

<img src="https://user-images.githubusercontent.com/4586392/45906019-4660f380-bdfb-11e8-832f-0ed9c4e55d77.png" width="350">
