### ISSUE TITLE
Indentation lost when pasting something syntactically incorrect

### ISSUE THREAD

**Issue by andreasabel** [JetBrains/intellij-arend#62]
The IDE seems to drop indentation when pasting something that is not syntactically correct.
For example pasting
```
\func isSubSkeleton {A : \Type} (xs ys : List A) : Bool =>
  {\elim xs {
  | nil        => true
  | (:: x xs)  => { \elim ys
    | (:: y ys)  => isSubSkeleton xs ys
    | nil        => false
  }}}
```
gives
```
\func isSubSkeleton {A : \Type} (xs ys : List A) : Bool =>
{\elim xs {
| nil        => true
| (:: x xs)  => { \elim ys
| (:: y ys)  => isSubSkeleton xs ys
| nil        => false
}}}
```
This is not the expected behavior; I'd expect I can freely edit my file without premature intervention from the IDE.

**Comment by sxhya** [comment]
There is a way to workaround this problem and paste a piece of code without formatting. To do this you may use the shortcut Ctrl+Shift+Alt+V (this shortcut can be changed in IDEA Settings).

I do not think that it is possible to significantly change the current behavior of code formatter. Let me explain why I think so. Code formatting engine in IntellijIDEA (which Arend plugin and all the other IDEA plugins use) takes as its input not plaintext but rather AST which is the output of parser. Of course, Arend parser can produce "meaningful" AST from the code, which is not syntactically correct. For this purpose it uses various parser-recovery heuristics. The problem with the piece of code mentioned by you is that pipe symbol ("|") in Arend is used not only for pattern-matching but also for copattern-matching and a number of other contexts. Thus, it seems not possible to implement the parser-recovery heuristic which would solve the problem for the code mentioned in your example.

It also seems to me that you try to use **\elim** keyword (which is allowed only at the top level of function definition) instead of **\case** (which can be used inside any Arend expression). You may want to take a look at [Arend standard library](https://github.com/JetBrains/arend-lib), where there are more examples of usages of pattern-matching.

**Comment by andreasabel** [comment]
Thanks @sxhya!

> shortcut Ctrl+Shift+Alt+V 

I guess this is what I would want as default, just raw pasting.  I would invoke the code formatter in a second step manually, if needed.  IDEA is not formatting as I am typing, so I expect it also not to format when I am pasting. (The designers of IDEA may have their reasons to choose the default differently; not to my taste.)

> You may want to take a look at Arend standard library,

Thanks, for the pointer, I was looking for examples but couldn't find some.
