### ISSUE TITLE
Better names in generated patterns

### ISSUE THREAD

**Issue by valis** [JetBrains/intellij-arend#88]
We can choose better names when generating patterns. For example, if the types begins with a symbol, it is better to use some other symbol. We can hard code some specific cases. For example, use `p` for paths.

Also, we can use the original name of the variable if the data type is recursive.

Before:
```
\func foo (n m : Nat) : Nat
```
After:
```
\func foo (n m : Nat) : Nat
  | 0, 0 => {?}
  | 0, suc m => {?}
  | suc n, 0 => {?}
  | suc n, suc m => {?}
```

Also, if the constructor has several recursive occurrences of the data type, we can use names `x1`, `x2`, `x3`, ... instead of `x`, `x1`, `x2`, ...

Before:
```
\func foo (t : Tree) : Nat
```
After:
```
\func foo (t : Tree) : Nat
  | leaf => {?}
  | branch t1 t2 => {?}
```

**Comment by sxhya** [comment]
The requested behavior contradicts current implementation. Currently we pick the "base" name of a pattern variable (i.e. the one which is fed into the fresh name generator) from the parameter declaration of the corresponding constructor (i.e. if the parameter is named -- then we use this name as the base name, otherwise we use the first letter of the corresponding data type). You propose that we use the name of the function argument instead. Could you specify in which situation your behavior should be preferred to the current one.

**Comment by valis** [comment]
1. If the constructor parameter has a name, we use it.
2. If the constructor parameter does not have a name, it is recursive, and there is a name of the original variable (which might not be the case, e.g., when we pattern match on an arbitrary expression in \case), then use the proposed behavior.
3. If 1 and 2 do not apply and the type name starts with a letter, use the lower case letter as before.
4. Use "p" for types of the form `a = b`.
5. If none of the above applies, use the default name.

**Comment by valis** [comment]
It does not work for functions defined with `\elim`. For example, `\func test (z : Nat) : Nat` generates the correct pattern `suc z`, but `\func test (z : Nat) : Nat \elim z` generates `suc n`.
